module.exports = [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'venv/**',
      'pygame_version/**',
      '**/*.min.js',
      'docs/js/_archived_complex/**'
    ]
  },
  {
    files: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // ブラウザ環境
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        SharedWorker: 'readonly',
        ServiceWorker: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        ArrayBuffer: 'readonly',
        Uint8Array: 'readonly',
        // Node.js環境
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        // Jest環境
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterAll: 'readonly',
        afterEach: 'readonly',
        jest: 'readonly',
        // アプリケーション固有のグローバル変数
        APP_CONFIG: 'readonly',
        io: 'readonly',
        OllamaGameEnhancer: 'readonly',
        GameEventBridge: 'readonly',
        GameEngine: 'readonly',
        GameState: 'readonly',
        ChallengeGenerator: 'readonly',
        ChallengeEvaluator: 'readonly',
        ChallengeGameIntegration: 'readonly',
        WeeklyChallenge: 'readonly',
        RankingController: 'readonly',
        RankingUI: 'readonly',
        PerformanceMetricsCollector: 'readonly',
        TutorialSystem: 'readonly',
        ErrorHandler: 'readonly',
        UIHelper: 'readonly',
        ConfigLoader: 'readonly',
        RetryHandler: 'readonly',
        NetworkMonitor: 'readonly',
        AnalyticsSystem: 'readonly',
        CSPReporter: 'readonly',
        WebSocketAuthManager: 'readonly'
      }
    },
    rules: {
      'no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_|^dummy'
      }],
      'no-console': 'off',
      'no-debugger': 'warn',
      'semi': ['error', 'always'],
      'quotes': ['error', 'single', { avoidEscape: true }],
      'indent': ['error', 2, { SwitchCase: 1 }],
      'comma-dangle': ['error', 'never'],
      'no-trailing-spaces': 'error',
      'eol-last': ['error', 'always'],
      'no-multiple-empty-lines': ['error', { max: 1 }]
    }
  }
];
